### ISSUE TITLE
Syntax error for schema administrator

### ISSUE THREAD

**Issue by IGPOlivier** [thomaseibner/snowflake-provisioning#4]
sf_create_obj schema commands generate the following grant for the schema ADM role:
GRANT CREATE TABLE IN SCHEMA MY_DB.MY_SCHEMA TO ROLE _SC_MY_DB_MY_SCHEMA_ADM_AR;
instead of
GRANT CREATE TABLE **ON** SCHEMA MY_DB.MY_SCHEMA TO ROLE _SC_MY_DB_MY_SCHEMA_ADM_AR;

same applies to all GRANT CREATE statements.

**Comment by thomaseibner** [comment]
I've fixed the issue in main.
